version: '3.9'
services:
  app:
    build: .
    container_name: crop_app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=crop
      # Email configuration for PHP Mailer - will be loaded from .env file
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: crop_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crop
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
